CREATE EXTERNAL TABLE raw.`royalties_audio`(
  `Codigo Unico` string,
  `Record Label` string,
  `PNAME` string,
  `Artist Name` string,
  `Individual Performer` string,
  `Performer Category` string,
  `Role` string,
  `Album Title` string,
  `Barcode/UPC` string,
  `Catalogue Number` string,
  `Format` string,
  `Main Release Date` string,
  `Country of Original Label` string,
  `Country of Recording` string,
  `Artist Nationality` string,
  `Recording Year` string,
  `Release Year` string,
  `Collection territories included` string,
  `Track on disc` string,
  `Number of disc` string,
  `Main Title` string,
  `Title Version` string,
  `ISRC Code` string,
  `Duration (in seconds)` string,
  `Date start` string,
  `Date end` string,
  `% Rights` string,
  `Publisher(s)` string,
  `Publisher(s) share` string,
  `Publishing Synch` string,
  `Publishing Mushroom %` string,
  `Publishing resto` string,
  `Album Agrupado` string,
  `ISWC` string,
  `Codigo SGAE` string,
  `Syncros catalogo` string,
  `Coments` string,
  `Kobalt` string,
  `Royalty rate Artist` string,
  `Royalty Artista 2` string,
  `Royalty Artista 3` string,
  `Royalty Artista 4` string,
  `Royalty Artista 5` string,
  `Royalty Mushroom` string,
  `Mail Envio Royalties Artista 1` string,
  `Mail Envio Royalties Artista 2` string,
  `Mail Envio Royalties Artista 3` string,
  `Mail Envio Royalties Artista 4` string,
  `Mail Envio Royalties Artista 5` string,
  `Periodicidad 1` string,
  `Periodicidad 2` string,
  `Periodicidad 3` string,
  `Periodicidad 4` string,
  `Periodicidad 5` string,
  `Royalty Synch 1` string,
  `Royalty Synch 2` string,
  `Royalty Synch 3` string,
  `Royalty Synch 4` string,
  `Royalty Synch 5` string,
  `Royalty Mush Synch` string,
  `Royalty physical 1` string,
  `Royalty physical 2` string,
  `Royalty physical 3` string,
  `Royalty physical 4` string,
  `Royalty physical 5` string,
  `Royalty Mush phy` string,
  `Observaciones` string
)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://mushroom-pillow-bi/data/raw/metadata/royalties_audio'
TBLPROPERTIES (
  'escapeChar'='\\', 
  'quoteChar'='\"', 
  'separatorChar'='\;', 
  'skip.header.line.count'='1')