CREATE EXTERNAL TABLE `raw.ventas_web_vieja`(
  `reference` string, 
  `order_detail_id` bigint, 
  `order_id` bigint, 
  `source` string, 
  `platform` string, 
  `sale_type` string, 
  `current_state_id` bigint, 
  `current_state` string, 
  `invoice_date` string, 
  `delivery_date` string, 
  `system_creation_date` string, 
  `id_address_invoice` bigint, 
  `id_address_country` bigint, 
  `country_iso_code` string, 
  `product_id` bigint, 
  `product_reference` string, 
  `id_order_detail` bigint, 
  `id_order` bigint, 
  `id_order_invoice` bigint, 
  `id_warehouse` bigint, 
  `id_shop` bigint, 
  `product_attribute_id` bigint, 
  `product_name` string, 
  `product_quantity` bigint, 
  `product_quantity_in_stock` bigint, 
  `product_quantity_refunded` bigint, 
  `product_quantity_return` bigint, 
  `product_quantity_reinjected` bigint, 
  `product_price` double, 
  `reduction_percent` double, 
  `reduction_amount` double, 
  `reduction_amount_tax_incl` double, 
  `reduction_amount_tax_excl` double, 
  `group_reduction` double, 
  `product_quantity_discount` double, 
  `product_ean13` bigint, 
  `product_upc` string, 
  `product_supplier_reference` string, 
  `product_weight` double, 
  `id_tax_rules_group` bigint, 
  `tax_computation_method` bigint, 
  `tax_name` string, 
  `tax_rate` bigint, 
  `ecotax` double, 
  `ecotax_tax_rate` bigint, 
  `discount_quantity_applied` bigint, 
  `download_hash` string, 
  `download_nb` bigint, 
  `download_deadline` string, 
  `total_price_tax_incl` double, 
  `total_price_tax_excl` double, 
  `unit_price_tax_incl` double, 
  `unit_price_tax_excl` double, 
  `total_shipping_price_tax_incl` double, 
  `total_shipping_price_tax_excl` double, 
  `purchase_supplier_price` double, 
  `original_product_price` double, 
  `original_wholesale_price` double, 
  `id_shop_group` bigint, 
  `id_carrier` bigint, 
  `id_lang` bigint, 
  `id_customer` bigint, 
  `id_cart` bigint, 
  `id_currency` bigint, 
  `id_address_delivery` bigint, 
  `secure_key` string, 
  `payment` string, 
  `conversion_rate` double, 
  `module` string, 
  `recyclable` bigint, 
  `gift` bigint, 
  `gift_message` string, 
  `mobile_theme` bigint, 
  `shipping_number` string, 
  `total_discounts` double, 
  `total_discounts_tax_incl` double, 
  `total_discounts_tax_excl` double, 
  `total_paid` double, 
  `total_paid_tax_incl` double, 
  `total_paid_tax_excl` double, 
  `total_paid_real` double, 
  `total_products` double, 
  `total_products_wt` double, 
  `total_shipping` double, 
  `total_shipping_tax_incl` double, 
  `total_shipping_tax_excl` double, 
  `carrier_tax_rate` double, 
  `total_wrapping` double, 
  `total_wrapping_tax_incl` double, 
  `total_wrapping_tax_excl` double, 
  `round_mode` bigint, 
  `round_type` bigint, 
  `invoice_number` bigint, 
  `delivery_number` bigint, 
  `valid` bigint, 
  `date_add` string, 
  `date_upd` string)
ROW FORMAT DELIMITED 
  FIELDS TERMINATED BY '\;' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://mushroom-pillow-bi/data/raw/sales_csv/ventas_web_vieja/'
TBLPROPERTIES (
  'CrawlerSchemaDeserializerVersion'='1.0', 
  'CrawlerSchemaSerializerVersion'='1.0', 
  'UPDATED_BY_CRAWLER'='ventas_web_vieja', 
  'areColumnsQuoted'='false', 
  'averageRecordSize'='1081', 
  'classification'='csv', 
  'columnsOrdered'='true', 
  'compressionType'='none', 
  'delimiter'='\;', 
  'objectCount'='1', 
  'recordCount'='4031', 
  'sizeKey'='4357942', 
  'skip.header.line.count'='1', 
  'typeOfData'='file')