--file	
--report_date -> "Cod Año - MEs" siempre el 1 mas un mes
--sale_date -> "Cod Año - Mes" siempre el 1
--quantity -> "U. post. dev"
--sale_type ->  "VENTAS_FISICAS"
--gross_revenue	-> "neto total"
--net_revenue	-> "ventas netas sello"
--product_id	-> "Referencia"
--isrc	 -> null
--song	-> XXXX (CALC)
--album	-> XXXX (CALC) (si no hay ningun match que ponga "Spinning Over You")
--artist	-> XXXX (CALC) (si no hay ningun match que ponga "reyko")
--platform	-> "Physical Store" matchear con plataforma_corregida
--"source"	-> GRAN_SOL
--country	-> 'Spain'
--continent	-> XXXX (CALC)
--agency	-> null
--is_licencing	-> false
--operation_type --> A CONFIRMAR EN CASO DE QUE SEA LP O CD tomar el formato del MP.
--stream_quality -> "N/A"

-- CURRENCY TYPE EUR