-- se llama ventas_a_tiendas_directas

--file	
--report_date -> igual a "sale date"
--sale_date -> 01-01-"Date" (solo tiene el ano)
--quantity -> "MP_Quantity"
--sale_type ->  "VENTAS_FISICAS"
--gross_revenue	-> "MP_Amount_pre_tax"
--net_revenue	-> "MP_Amount_pre_tax"
--product_id	-> "MP_ref_ID"
--isrc	 -> null
--song	-> XXXX (CALC)
--album	-> XXXX (CALC) (si no hay ningun match que ponga "Spinning Over You")
--artist	-> XXXX (CALC) (si no hay ningun match que ponga "reyko")
--platform	-> "Mushroom Pillow Store Web" matchear con plataforma_corregida
--"source"	-> VENTAS_WEB_ANTIGUA
--country	-> 'ESPANA'
--continent	-> XXXX (CALC)
--agency	-> null
--is_licencing	-> false
--operation_type --> A CONFIRMAR EN CASO DE QUE SEA LP O CD tomar el formato del MP.
--stream_quality -> "N/A"

-- EXCHANGE RATE EUR
